// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package core

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/neatlab/neatio/common"
	"github.com/neatlab/neatio/common/hexutil"
	"github.com/neatlab/neatio/common/math"
)

var _ = (*genesisAccountMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (g GenesisAccount) MarshalJSON() ([]byte, error) {
	type GenesisAccount struct {
		Code                 hexutil.Bytes               `json:"code,omitempty"`
		Storage              map[storageJSON]storageJSON `json:"storage,omitempty"`
		Balance              *math.HexOrDecimal256       `json:"balance" gencodec:"required"`
		Nonce                math.HexOrDecimal64         `json:"nonce,omitempty"`
		Amount               *math.HexOrDecimal256       `json:"amount,omitempty"`
		DelegateBalance      *big.Int                    `json:"delegate,omitempty"`
		DepositProxiedDetail map[common.Address]*big.Int `json:"proxiedList,omitempty"`
		Candidate            bool                        `json:"candidate,omitempty"`
		Commission           uint8                       `json:"commission,omitempty"`
		PrivateKey           hexutil.Bytes               `json:"secretKey,omitempty"`
	}
	var enc GenesisAccount
	enc.Code = g.Code
	if g.Storage != nil {
		enc.Storage = make(map[storageJSON]storageJSON, len(g.Storage))
		for k, v := range g.Storage {
			enc.Storage[storageJSON(k)] = storageJSON(v)
		}
	}
	enc.Balance = (*math.HexOrDecimal256)(g.Balance)
	enc.Nonce = math.HexOrDecimal64(g.Nonce)
	enc.Amount = (*math.HexOrDecimal256)(g.Amount)
	enc.DelegateBalance = g.DelegateBalance
	enc.DepositProxiedDetail = g.DepositProxiedDetail
	enc.Candidate = g.Candidate
	enc.Commission = g.Commission
	enc.PrivateKey = g.PrivateKey
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (g *GenesisAccount) UnmarshalJSON(input []byte) error {
	type GenesisAccount struct {
		Code                 *hexutil.Bytes              `json:"code,omitempty"`
		Storage              map[storageJSON]storageJSON `json:"storage,omitempty"`
		Balance              *math.HexOrDecimal256       `json:"balance" gencodec:"required"`
		Nonce                *math.HexOrDecimal64        `json:"nonce,omitempty"`
		Amount               *math.HexOrDecimal256       `json:"amount,omitempty"`
		DelegateBalance      *big.Int                    `json:"delegate,omitempty"`
		DepositProxiedDetail map[common.Address]*big.Int `json:"proxiedList,omitempty"`
		Candidate            *bool                       `json:"candidate,omitempty"`
		Commission           *uint8                      `json:"commission,omitempty"`
		PrivateKey           *hexutil.Bytes              `json:"secretKey,omitempty"`
	}
	var dec GenesisAccount
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Code != nil {
		g.Code = *dec.Code
	}
	if dec.Storage != nil {
		g.Storage = make(map[common.Hash]common.Hash, len(dec.Storage))
		for k, v := range dec.Storage {
			g.Storage[common.Hash(k)] = common.Hash(v)
		}
	}
	if dec.Balance == nil {
		return errors.New("missing required field 'balance' for GenesisAccount")
	}
	g.Balance = (*big.Int)(dec.Balance)
	if dec.Nonce != nil {
		g.Nonce = uint64(*dec.Nonce)
	}
	if dec.Amount != nil {
		g.Amount = (*big.Int)(dec.Amount)
	}
	if dec.DelegateBalance != nil {
		g.DelegateBalance = dec.DelegateBalance
	}
	if dec.DepositProxiedDetail != nil {
		g.DepositProxiedDetail = dec.DepositProxiedDetail
	}
	if dec.Candidate != nil {
		g.Candidate = *dec.Candidate
	}
	if dec.Commission != nil {
		g.Commission = *dec.Commission
	}
	if dec.PrivateKey != nil {
		g.PrivateKey = *dec.PrivateKey
	}
	return nil
}
